version: '3'

volumes:
  msdata:

services:

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - "1883:1883"
    volumes:
      - "msdata:/mosquitto/data"
      - "${PWD}/docker/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "${PWD}/docker/certs/:/certs:ro"
