apiVersion: v1
kind: Pod
metadata:
  labels:
    run: iot-mqtt-bridge
  name: iot-mqtt-bridge
  namespace: iot
spec:
  containers:
  - name: iot-mqtt-bridge
    image: wallingford.pmel.noaa.gov:8443/iot/iot-mqtt-bridge:0.3
    
    tty: true