apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/temp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-claim-test
  namespace: default
spec:
  containers:
    - name: volume-test
      image: nginx:stable-alpine
      volumeMounts:
        - name: data-pv-storage
          mountPath: /data
      ports:
        - containerPort: 80
  volumes:
    - name: data-pv-storage
      persistentVolumeClaim:
        claimName: data-pv-claim
