apiVersion: v1
kind: PersistentVolume
metadata:
  name: erddap-data-pv-storage
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-cluster-1-iot-data-landing-3a105b37-mb58
    fsType: ext4