---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster-1
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: nodeport
        tls: false
      - name: tls
        port: 9093
        type: nodeport
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          brokers:
          - broker: 0
            advertisedHost: localhost
            advertisedPort: 31314

    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
      - id: 1
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    jvmOptions:
      -Xms: 256m
      -Xmx: 256m
    resources:
      requests:
        memory: 200m
        cpu: 1
      limits:
        memory: 400m
        cpu: 5
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
    jvmOptions:
      -Xms: 256m
      -Xmx: 256m
    resources:
      requests:
        memory: 200m
        cpu: 1
      limits:
        memory: 400m
        cpu: 5
    config:
      ssl.endpoint.identification.algorithm: ""
  entityOperator:
    topicOperator: {}
    userOperator: {}

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-1-kafka
spec:
  type: ClusterIP
  selector:
    strimzi.io/cluster: cluster-1
    strimzi.io/kind: Kafka
    strimzi.io/name: cluster-1
  ports:
  - name: plain
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: tls
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: external
    port: 9094
    targetPort: 9094
    protocol: TCP