---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: iot-data-landing
spec:
  kafka:
    version: 3.3.2
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.3.2"
      ssl.endpoint.identification.algorithm: ""
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
      - id: 1
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    resources:
      requests:
        memory: 256m
        cpu: 1
      limits:
        memory: 512m
        cpu: 2
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
    jvmOptions:
      -Xms: 256m
      -Xmx: 256m
    resources:
      requests:
        memory: 256Mi
        cpu: 1
      limits:
        memory: 512Mi
        cpu: 2
    config:
      ssl.endpoint.identification.algorithm: ""
  entityOperator:
    topicOperator: {}
    userOperator: {}
