apiVersion: v1
kind: Pod
metadata:
  labels:
  name: mqtt-bridge
spec:
  containers:
  - name: mqtt-bridge
    image: harbor.axds.co/iot-data-landing/mqtt_bridge
    #image: iot-data-landing-registry:5000/mqtt-bridge:1.0.4
    imagePullPolicy: Always
    env:
      - name: MQTT_BRIDGE_MQTT_BROKER
        valueFrom:
          configMapKeyRef:
            name: mqtt-bridge
            key: mqtt_broker
      - name: MQTT_BRIDGE_MQTT_PORT
        valueFrom:
          configMapKeyRef:
            name: mqtt-bridge
            key: mqtt_port
      - name: MQTT_BRIDGE_MQTT_TOPIC_FILTER
        valueFrom:
          configMapKeyRef:
            name: mqtt-bridge
            key: mqtt_topic_filter
      - name: MQTT_BRIDGE_MQTT_TOPIC_SUBSCRIPTION
        valueFrom:
          configMapKeyRef:
            name: mqtt-bridge
            key: mqtt_topic_subscription
      - name: MQTT_BRIDGE_KNATIVE_BROKER
        value: http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/default