apiVersion: v1
kind: PersistentVolume
metadata:
  name: erddap-data-pv-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/erddap/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erddap-data-pv-claim
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: erddap
spec:
  ports:
    - name: http
      # protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      # protocol: TCP
      port: 8443
      targetPort: 8443
  # ports:
  #   - protocol: TCP
  #     name: http
  #     port: 8080
  #     name: https
  #     port: 8443
  selector:
    app: erddap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erddap
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erddap
  template:
    metadata:
      labels:
        app: erddap
    spec:
      containers:
        - name: erddap
          image: axiom/docker-erddap:2.18
          env:
            - name: ERDDAP_MAX_MEMORY
              value: 2G
            - name: ERDDAP_MIN_MEMORY
              value: 1G
            - name: ERDDAP_baseUrl
              value: http://localhost:8081
            - name: ERDDAP_baseHttpsUrl
              value: https://localhost:8444
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: erddap-data-pv-storage
              mountPath: /erddapData
            - name: erddap-config-pv-storage
              mountPath: /usr/local/tomcat/content/erddap/datasets.xml
            - name: erddap-server-pv-storage
              mountPath: /usr/local/tomcat/conf/server.xml
            - name: erddap-ssl-crt-pv-storage
              mountPath: /usr/local/tomcat/conf/ssl.crt
              # subPath: ssl.crt
            - name: erddap-ssl-key-pv-storage
              mountPath: /usr/local/tomcat/conf/ssl.key
              # subPath: ssl.key
      volumes:
        - name: erddap-data-pv-storage
          persistentVolumeClaim:
            claimName: erddap-data-pv-claim
        - name: erddap-config-pv-storage
          hostPath:
            path: /data/erddap/conf/datasets.xml
            type: File
        - name: erddap-server-pv-storage
          hostPath:
            path: /data/erddap/conf/server.xml
            type: File
        - name: erddap-ssl-crt-pv-storage
          hostPath:
            path: /data/erddap/certs/ssl.crt
            type: File
        - name: erddap-ssl-key-pv-storage
          hostPath:
            path: /data/erddap/certs/ssl.key
            type: File
        # - name: erddap-ssl-crt
        #   hostPath:
        #     path: /home/junge/derek/Software/iot-data-landing/dev/erddap/certs/ssl.crt
        # - name: erddap-ssl-key
        #   hostPath:
        #     path: /home/junge/derek/Software/iot-data-landing/dev/erddap/certs/ssl.key
