apiVersion: v1
kind: PersistentVolume
metadata:
  name: erddap-data-pv-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/erddap/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erddap-data-pv-claim
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: erddap
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
  selector:
    app: erddap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erddap
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erddap
  template:
    metadata:
      labels:
        app: erddap
    spec:
      containers:
        - name: erddap
          image: axiom/docker-erddap:2.18
          env:
            - name: ERDDAP_MAX_MEMORY
              value: 2G
            - name: ERDDAP_MIN_MEMORY
              value: 1G
            - name: ERDDAP_baseUrl
              value: http://localhost:8081
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: erddap-data-pv-storage
              mountPath: /erddapData
            - name: erddap-config-pv-storage
              mountPath: /usr/local/tomcat/content/erddap/datasets.xml
      volumes:
        - name: erddap-data-pv-storage
          persistentVolumeClaim:
            claimName: erddap-data-pv-claim
        - name: erddap-config-pv-storage
          hostPath:
            path: /data/erddap/conf/datasets.xml
            type: File
