# Knative Eventing Trigger to trigger the helloworld-python service
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: iot-erddap-envds
  # namespace: iot
spec:
  broker: default
  # broker: iot-broker
  filter:
    attributes:
      type: gov.noaa.pmel.acg.data.insert.envds.v2
      # source: /sensor/MockCo/Sensor-1/1234
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: iot-erddap-envds
      namespace: iot
    uri: /insert