apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: erddap-insert
spec:
  template:
    spec:
      containers:
      - image: iot-data-landing-registry:5000/erddap-insert:1.0.12
        imagePullPolicy: Always
        env:
          - name: IOT_ERDDAP_INSERT_URL
            value: "http://erddap:8080/erddap/tabledap"
          - name: IOT_ERDDAP_INSERT_AUTHOR
            value: "super_secret_author"
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: erddap-insert
spec:
  broker: default
  filter:
    attributes:
      type: gov.noaa.pmel.acg.data.insert.envds.v2
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: erddap-insert
