apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: qc-run
spec:
  template:
    spec:
      containers:
      - image: harbor.axds.co/iot-data-landing/qc_run
        imagePullPolicy: Always
        env:
          - name: IOT_QC_RUN_KNATIVE_BROKER
            value: http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/default
          - name: IOT_QC_RUN_BUCKET
            value: iot-data-landing
          #- name: IOT_QC_RUN_ENDPOINT
          #  value: http://minio:9000
          #- name: IOT_QC_RUN_USER
          #  valueFrom:
          #    secretKeyRef:
          #      name: minio
          #      key: MINIO_ROOT_USER
          #- name: IOT_QC_RUN_PASS
          #  valueFrom:
          #    secretKeyRef:
          #      name: minio
          #      key: MINIO_ROOT_PASSWORD
          - name: IOT_QC_RUN_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: gcp-secret-key 
                key: pmel-iot-658e7c2cdb27.json
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: qc-run
spec:
  broker: default
  filter:
    attributes:
      type: gov.noaa.pmel.acg.data.insert.envds.v2
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: qc-run
